services:
  - type: web
    name: predicto001-frontend
    env: static
    buildCommand: null
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 